version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/global/humanize-writing"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
